---
- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    group: docker
    mode: 0755
  with_items:
    - "/opt/mongodb"

- name: Create initial configuration
  template:
    src: mongod_initial.conf.j2
    dest: "/opt/mongodb/mongod.conf.orig"
    #  when: not mongod_config.stat.exists
