---
- name: Configuring directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ mongodb_system_user }}"
    group: "{{ mongodb_system_group }}"
    mode: 0755
  with_items:
    - "{{ mongodb_database_dir }}"
    - "{{ mongodb_log_dir }}"

# TODO remove locale?
- name: Set default locale
  lineinfile:
    dest: /etc/default/locale
    regexp: "LC_ALL"
    line: 'LC_ALL="en_US.UTF-8"'

- name: Update locale
  command: update-locale LC_ALL=en_US.UTF-8

- stat:
    path: /etc/mongo_key
  register: mongod_config

- name: Create initial configuration
  template:
    src: mongod_initial.conf.j2
    dest: /etc/mongod.conf
  when: not mongod_config.stat.exists

- name: Enable mongo service
  service:
    name: mongod
    state: started
    enable: yes
