---
- name: Make sure that docker is installed and running
  service:
    name: docker
    state: started

- name: Download and run MongoDB instance
  docker_container:
    name: mongo
    image: "mongo:{{ mongodb_version }}"
    state: started
    restart_policy: unless-stopped
    ports: "{{ mongodb_port }}:27017"
    volumes:
      - "/opt/mongodb:/data/db:rw"
      - "/opt/mongodb/mongod.conf.orig:/etc/mongod.conf.orig:ro"

- name: Get IP MongoDB instance container
  shell: "docker inspect -f '{% raw %}{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}{% endraw %}' mongo"
  register: mongodb_address
  changed_when: false

- name: "Set fact IP MongoDB instance container"
  set_fact:
    mongodb_container_address: "{{ mongodb_address.stdout }}"
