---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mongodb_dependencies }}"

- name: Add mongodb repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  when: ansible_pkg_mgr == "apt"

- name: Add mongodb repository [Ubuntu]
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Add mongodb repository [Centos]
  template:
    src: mongodb.repo.j2
    dest: /etc/yum.repos.d/mongodb.repo
  when: ansible_pkg_mgr == "yum"

- name: Install mongodb
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mongodb_packages }}"
