---
- name: install needed packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl

- name: create mongodb_exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongodb_system_user }}"
    group: "{{ mongodb_system_group }}"
    mode: 0755
  with_items:
    - "{{ mongodb_exporter_root_dir }}"
    - "{{ mongodb_exporter_dist_dir }}"
    - "{{ mongodb_exporter_bin_dir }}"
    - "{{ mongodb_exporter_log_dir }}"

- name: download mongodb_exporter binary to local folder
  become: no
  get_url:
    url: "{{ mongodb_exporter_url }}"
    dest: /tmp/mongodb_exporter-linux-amd64
    validate_certs: no
  run_once: true
  delegate_to: localhost

- name: propagate mongodb_exporter binary
  copy:
   src: /tmp/mongodb_exporter-linux-amd64
   dest: "{{ mongodb_exporter_dist_dir }}"

- name: create symlink to the current release
  file:
    src: "{{ mongodb_exporter_dist_dir }}/mongodb_exporter-linux-amd64"
    path: "{{ mongodb_exporter_bin_dir }}"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/mongodb_exporter.service.j2
    dest: /etc/systemd/system/mongodb_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb_exporter

- name: ensure mongodb_exporter service is enabled
  service:
    name: mongodb_exporter
    enabled: yes
