---
- name: Ensure directory exists
  file:
    path: "/etc/telegraf/telegraf.d"
    state: directory

- name: Create telegraf plugin config
  template:
    src: mongodb_telegraf.conf.j2
    dest: /etc/telegraf/telegraf.d/mongodb.conf

