---
- name: Download mongodb exporter binary to local folder
  become: no
  get_url:
    url: "https://github.com/dcu/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-linux-amd64"
    dest: "/tmp"
  run_once: true
  delegate_to: localhost

- name: Propagate mongodb exporter binariey
  copy:
    src: "/tmp/mongodb_exporter-linux-amd64"
    dest: "/opt/mongodb_exporter"
    mode: 0755
  notify:
    - restart mongodb exporter

- name: Copy the mongodb exporter systemd service file
  template:
    src: mongodb_exporter.service.j2
    dest: /etc/systemd/system/mongodb_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
  - restart mongodb exporter

- name: Ensure mongodb exporter is enabled on boot
  service:
    name: mongodb_exporter
    enabled: yes
  when: ansible_virtualization_type != 'docker'
