---
- name: Flush handlers to restart mongodb if necessary
  meta: flush_handlers

- pause:
    prompt: "Wait for mongo"
    seconds: 5

#- name: Wait for mongo
#  wait_for:
#    host: "{{ mongodb_address }}"
#    port: "{{ mongodb_port }}"

- name: Check if replica if configured
  command: "mongo {{ mongodb_replica_name }} --eval 'rs.conf();'"
  register: replica_conf
  ignore_errors: True

- block:
  - name: Start replica set
    command: "mongo {{ mongodb_replica_name }} --eval 'rs.initiate();'"
  
  - set_fact:
      arbiter_address: "{{ hostvars[mongodb_replica_arbiter]['ansible_' + mongodb_interface]['ipv4']['address'] }}" 
  
  - name: Add arbiter node
    command: "mongo {{ mongodb_replica_name }} --eval 'rs.addArb(\"{{ arbiter_address }}\");'"
    when: mongodb_replica_arbiter != None
  
  - name: Add data nodes
    command: "mongo {{ mongodb_replica_name }} --eval 'rs.add(\"{{ hostvars[item]['ansible_' + mongodb_interface]['ipv4']['address'] }}\");'"
    with_items: "{{ mongodb_replica_secondary_nodes }}"
  
  - pause:
      prompt: "Wait for election to finish" 
      seconds: 5
  when: "'no replset config has been received' in replica_conf.stdout"
