---
- name: Ensure Mongodb admin exists
  mongodb_user:
    database: admin
    login_host: "{{ mongodb_container_address }}"
    login_port: "{{ mongodb_port }}"
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: userAdmin,clusterAdmin,userAdminAnyDatabase
    state: present
  changed_when: false

- name: Create Mongodb users
  mongodb_user:
    database: "{{ item.db }}"
    login_host: "{{ mongodb_container_address}}"
    login_port: "{{ mongodb_port }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    roles: "{{ item.roles | default('readWrite') }}"
    state: present
  with_items: "{{ mongodb_users }}"
  when: mongodb_create_users
