---
- name: Ensure admin exists
  mongodb_user: 
    database: admin
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: userAdmin,clusterAdmin,userAdminAnyDatabase
    state: present
  ignore_errors: true

#- name: Create users
#  mongodb_user: 
#    database: "{{ item.value.db }}"
#    login_user: "{{ mongodb_admin_user }}"
#    login_password: "{{ mongodb_admin_password }}"
#    name: "{{ item.value.name }}"
#    password: "{{ item.value.pass }}"
#    roles: readWrite
#    state: present
#  with_dict: "{{ mongodb_users }}"

