---
- name: restart mongodb
  service:
    name: mongod
    state: restarted

- name: restart mongodb_exporter
  service:
    name: mongodb_exporter
    state: restarted

- name: reload mongodb_exporter
  service:
    name: mongodb_exporter
    state: reloaded

